"""favoritemovies table

Revision ID: 08f6188428a2
Revises: 5a60743ac612
Create Date: 2024-04-29 22:06:17.111597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f6188428a2'
down_revision = '5a60743ac612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('shortDescription', sa.String(length=140), nullable=False),
    sa.Column('kp_rating', sa.Float(), nullable=False),
    sa.Column('imdb_rating', sa.Float(), nullable=False),
    sa.Column('ageRating', sa.Integer(), nullable=False),
    sa.Column('posterUrl', sa.String(length=140), nullable=False),
    sa.Column('posterPreviewUrl', sa.String(length=140), nullable=False),
    sa.Column('genres', sa.String(length=140), nullable=False),
    sa.Column('countries', sa.String(length=140), nullable=False),
    sa.Column('releaseStart', sa.Integer(), nullable=False),
    sa.Column('releaseEnd', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_movie_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_movie_user_id'))

    op.drop_table('favorite_movie')
    # ### end Alembic commands ###
