"""Fix id

Revision ID: 0ae7fa09d980
Revises: 7b379419e6d2
Create Date: 2024-05-25 21:46:41.869993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae7fa09d980'
down_revision = '7b379419e6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_movie', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_movie', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
