"""empty message

Revision ID: 13f72fe469c1
Revises: 08f6188428a2
Create Date: 2024-05-01 00:36:32.100553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f72fe469c1'
down_revision = '08f6188428a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('shortDescription',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('kp_rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('imdb_rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('ageRating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('posterUrl',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('posterPreviewUrl',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('countries',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('releaseStart',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('releaseEnd',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.alter_column('releaseEnd',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('releaseStart',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('countries',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('posterPreviewUrl',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('posterUrl',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('ageRating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('imdb_rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kp_rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('shortDescription',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
