"""Recreate user_preference table

Revision ID: 5752813f2c2b
Revises: f87e8d60a542
Create Date: 2024-05-25 02:28:16.136159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5752813f2c2b'
down_revision = 'f87e8d60a542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('countries', sa.String(length=500), nullable=True),
    sa.Column('releaseYearsStart', sa.String(length=500), nullable=True),
    sa.Column('preferences_chosen', sa.Boolean(create_constraint=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preference_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preference_user_id'))

    op.drop_table('user_preference')
    # ### end Alembic commands ###
