"""Add kp_id films

Revision ID: 7b379419e6d2
Revises: 9094ccf387f4
Create Date: 2024-05-25 21:22:01.700733

"""
from alembic import op
import sqlalchemy as sa


# revision kp_identifiers, used by Alembic.
revision = '7b379419e6d2'
down_revision = '9094ccf387f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kp_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.drop_column('kp_id')

    # ### end Alembic commands ###
