"""Add rate

Revision ID: 9094ccf387f4
Revises: 5752813f2c2b
Create Date: 2024-05-25 16:28:59.703694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9094ccf387f4'
down_revision = '5752813f2c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_movie_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_movie_user_id'))

    op.drop_table('rate_movie')
    # ### end Alembic commands ###
